# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.example.unicom.ppl
canonical: http://example.org/unicom/ppl
name: IDMP_IG
title: "PPL Examples"
description: Sample IDMP data 
status: draft
version: 0.1.0
fhirVersion: 4.6.0
copyrightYear: 2021+
releaseLabel: current
publisher:
    name: Unicom Project
    url: https://unicom-project.eu/
dependencies:
#   hl7.fhir.r5.core : dev
#    hl7.fhir.r5.expansions : current
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html

  
  