# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.example.unicom.ppl
canonical: http://example.org/unicom/ppl
name: IDMP_IG
title: "PPL Examples"
description: Sample IDMP data 
status: draft
version: 0.1.0
fhirVersion: 4.6.0
copyrightYear: 2021+
releaseLabel: current
publisher:
    name: Unicom Project
    url: https://unicom-project.eu/
dependencies:
#   hl7.fhir.r5.core : dev
#    hl7.fhir.r5.expansions : current
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html

groups:
  Group A:
    name: Betaklav (Estonia)
    resources:
    - Bundle/10e18b90-c5ff-4921-acae-db0a9f85cc79

  Group B:
    name: Betaklav (Sweden)
    resources:
    - Bundle/20131217000072  

  Group C:
    name: Cefuroxime
    description: Cefuroxime as specified in Estonia.  This does not use a Bundle.
    resources:
    - MedicinalProductDefinition/CefuroximeMIP1500MG-EE	
    - ManufacturedItemDefinition/CefuroximeMIP1500MG-EE-ManItem001	
    - RegulatedAuthorization/CefuroximeMIP1500MG-EE-MarketingAuthorisation	
    - PackagedProductDefinition/CefuroximeMIP1500MG-EE-Package001
    - Ingredient/cefuroxime-1500mg-Ingredient	
    - AdministrableProductDefinition/cefuroxime-1500mg-solution-vial

  Group D:
    name: CanifugCremolum EE
    description: Canestan Combi in its Estonian form.  This has been built as a Transaction Bundle so all resources are independant, but are managed as a single transaction - if one part fails it all fails.
    resources:
    - Bundle/CanifugCremolum-EE-Bundle 



  
  